backend:
  name: github
  repo: chimgandacha/qimiz
  branch: main
site_id  '8a922642-80b0-4911-b7f4-ba5ba503bbf1'
media_folder: "images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "index.html"
        label: "Главная страница"
        name: "index"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Цена комнат", name: "price", widget: "string" }
